# Generated by Django 4.0.6 on 2022-08-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_myuser_address_remove_myuser_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Profile/%Y/%m/%d/', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Super User'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='OTP'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='otp_verify',
            field=models.BooleanField(default=False),
        ),
    ]
